### ISSUE TITLE
Calling cv2.imshow causes plt.imshow to throw NSInvalidArgumentException on MacOS High Sierra

### ISSUE THREAD

**Issue by keithlee96** [skvark/opencv-python#115]
### Expected behaviour

When I called cv2.imshow with an image, then called matplotlib.pyplot.imshow, I expected both openCV and matplotlib to display the image in their respective formats.

### Actual behaviour

When I called cv2.imshow with an image, then called matplotlib.pyplot.imshow, a NSInvalidArgumentException error is thrown.

Write here what went wrong.

### Steps to reproduce

main.py:

    import numpy as np
    import cv2

    # Prevents mac import issue
    from sys import platform as sys_pf
    if sys_pf == 'darwin':
      import matplotlib as mpl
      mpl.use('TkAgg')

    import matplotlib.pyplot as plt

    randomImage = np.random.random((90,90))

    cv2.imshow('random image', randomImage)
    plt.imshow(randomImage, cmap = 'gray', interpolation = 'bicubic')

If you run `python main.py` in the command line, it returns the following:

    2018-08-08 15:36:17.202 python[33590:1608842] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7feb3c15af30
    2018-08-08 15:36:17.206 python[33590:1608842] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7feb3c15af30'
    *** First throw call stack:
    (
      0   CoreFoundation                      0x00007fff3e71b33b __exceptionPreprocess + 171
      1   libobjc.A.dylib                     0x00007fff65477942 objc_exception_throw + 48
      2   CoreFoundation                      0x00007fff3e7b25e4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
      3   CoreFoundation                      0x00007fff3e692f03 ___forwarding___ + 1443
      4   CoreFoundation                      0x00007fff3e6928d8 _CF_forwarding_prep_0 + 120
      5   libtk8.6.dylib                      0x000000010bdc21f2 TkpInit + 408
      6   libtk8.6.dylib                      0x000000010bd31aac Initialize + 2454
      7   _tkinter.cpython-37m-darwin.so      0x000000010bb93dc4 Tcl_AppInit + 84
      8   _tkinter.cpython-37m-darwin.so      0x000000010bb93a98 _tkinter_create + 1144
      9   Python                              0x000000010250242e _PyMethodDef_RawFastCallKeywords + 430
      10  Python                              0x000000010250199a _PyCFunction_FastCallKeywords + 42
      11  Python                              0x00000001025c128e call_function + 782
      12  Python                              0x00000001025be240 _PyEval_EvalFrameDefault + 25152
      13  Python                              0x00000001025c1d76 _PyEval_EvalCodeWithName + 2422
      14  Python                              0x000000010250153b _PyFunction_FastCallDict + 523
      15  Python                              0x000000010250280f _PyObject_Call_Prepend + 143
      16  Python                              0x0000000102550cd1 slot_tp_init + 145
      17  Python                              0x000000010254c649 type_call + 297
      18  Python                              0x00000001025017b1 _PyObject_FastCallKeywords + 433
      19  Python                              0x00000001025c1172 call_function + 498
      20  Python                              0x00000001025be387 _PyEval_EvalFrameDefault + 25479
      21  Python                              0x0000000102501dd0 function_code_fastcall + 128
      22  Python                              0x00000001025c129b call_function + 795
      23  Python                              0x00000001025be240 _PyEval_EvalFrameDefault + 25152
      24  Python                              0x00000001025c1d76 _PyEval_EvalCodeWithName + 2422
      25  Python                              0x000000010250153b _PyFunction_FastCallDict + 523
      26  Python                              0x000000010250280f _PyObject_Call_Prepend + 143
      27  Python                              0x0000000102501ac7 PyObject_Call + 135
      28  Python                              0x00000001025be551 _PyEval_EvalFrameDefault + 25937
      29  Python                              0x00000001025c1d76 _PyEval_EvalCodeWithName + 2422
      30  Python                              0x0000000102501961 _PyFunction_FastCallKeywords + 257
      31  Python                              0x00000001025c129b call_function + 795
      32  Python                              0x00000001025be2e1 _PyEval_EvalFrameDefault + 25313
      33  Python                              0x0000000102501dd0 function_code_fastcall + 128
      34  Python                              0x00000001025c129b call_function + 795
      35  Python                              0x00000001025be2e1 _PyEval_EvalFrameDefault + 25313
      36  Python                              0x00000001025c1d76 _PyEval_EvalCodeWithName + 2422
      37  Python                              0x0000000102501961 _PyFunction_FastCallKeywords + 257
      38  Python                              0x00000001025c129b call_function + 795
      39  Python                              0x00000001025be2e1 _PyEval_EvalFrameDefault + 25313
      40  Python                              0x00000001025c1d76 _PyEval_EvalCodeWithName + 2422
      41  Python                              0x0000000102501961 _PyFunction_FastCallKeywords + 257
      42  Python                              0x00000001025c129b call_function + 795
      43  Python                              0x00000001025be387 _PyEval_EvalFrameDefault + 25479
      44  Python                              0x00000001025c1d76 _PyEval_EvalCodeWithName + 2422
      45  Python                              0x00000001025b7f24 PyEval_EvalCode + 100
      46  Python                              0x00000001025f5301 PyRun_FileExFlags + 209
      47  Python                              0x00000001025f4bab PyRun_SimpleFileExFlags + 859
      48  Python                              0x0000000102612c0c pymain_main + 8060
      49  Python                              0x0000000102613071 _Py_UnixMain + 129
      50  libdyld.dylib                       0x00007fff66064115 start + 1
      51  ???                                 0x0000000000000002 0x0 + 2
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

### operating system
MacOS High Sierra (64 bit)

### opencv-python version
3.4.1

**Comment by skvark** [comment]
There are some issues in your code:

- you need to use waitKey, for example `cv2.waitKey(0)`, immediately after `cv2.imshow()`
- I believe that the order of the function calls is important

Fixed code:

```
plt.imshow(randomImage, cmap = 'gray', interpolation = 'bicubic')
cv2.imshow('random image', randomImage)
cv2.waitKey(0)
```

If the above does not work, then you can't use both simultaneously.

**Comment by keithlee96** [comment]
@skvark Adding a line that runs after the error is thrown does not fix it

**Comment by skvark** [comment]
Thanks for the clarification.

If there's a bug in OpenCV, you should open an issue to the actual OpenCV repository: https://github.com/opencv/opencv/

**Comment by KayHS** [comment]
Im also having this issue please see. https://github.com/skvark/opencv-python/issues/134
