### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by shibutamang** [skvark/opencv-python#181]
### Expected behaviour

Write here how did you expect the library to function.

### Actual behaviour

Write here what went wrong.

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

**Comment by Trooper247** [comment]
**Expected behavior:**
Well i want to import it first and i got this error:
File "C:\Users\Dawid\AppData\Local\Programs\Python\Python37\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: the specified module could not be found

I have WIN 10 updated yesterday.x64 Python 3.7.2 and Opencv latest version that is 4.0.0.21

**Comment by skvark** [comment]
Do you have Visual C++ redistributable 2015 installed? https://www.microsoft.com/en-us/download/details.aspx?id=48145

See this issue for more help: https://github.com/skvark/opencv-python/issues/174

These issues are usually easily solved with dependency walker (because you have a missing dependency).

**Comment by Trooper247** [comment]
I have installed 2015 version of Visuall but it still doesn't work. In a matter of dependencies have the program but I don't fully understand what file I need to check. I only checked Opencv dll file and it seemed just fine.

**Comment by skvark** [comment]
You have to open the cv2.cp37-win_amd64.pyd file located at C:\Users\Dawid\AppData\Local\Programs\Python\Python37\lib\site-packages\

**Comment by Trooper247** [comment]
I'm gonna check it later today's evening when I come back

**Comment by Trooper247** [comment]
**Looks like i miss 3 dll files** 
![image](https://user-images.githubusercontent.com/27973307/54944015-df9bce80-4f32-11e9-8719-76f7919283a4.png)
Should i download them manually and put in opencv directory ?

**Comment by skvark** [comment]
Never download arbitrary dll's from anywhere because they are most likely malware. I believe that this media feature pack is missing from your computer: https://www.microsoft.com/en-us/download/details.aspx?id=53356

**Comment by Trooper247** [comment]
Works, thanks for support!
